export const CandidatesData = [
  {
    id: 1,
    name: "Jane Õun",
    email: "janeoun@gmail.com",
    phone: "+37256438567",
    sex: "female",
    job_type: "full time",
    location: "Tallinn",
    recruiter_name: "Kirsti Kask",
    image: "",
    avatar_name: "JÕ",
    candidates: "shortlisted",
    phase: "Startup",
    appliedDate: "12/04/2022",
    status: "active",
  },
  {
    id: 2,
    name: "Romet Tamm",
    email: "romettamm@gmail.com",
    phone: "37254789054",
    sex: "male",
    job_type: "full time",
    location: "Tallinn",
    recruiter_name: "Janne Hunt",
    image: "",
    avatar_name: "RT",
    candidates: "sent",
    phase: "Startup",
    appliedDate: "13/04/2022",
    status: "active",
  },
  {
    id: 3,
    name: "Jesse Hurt",
    email: "jesse@gmail.com",
    phone: "37253437569",
    sex: "female",
    job_type: "part time",
    location: "Tallinn",
    recruiter_name: "Janne Hunt",
    image: "",
    avatar_name: "JH",
    candidates: "1st Interview",
    phase: "Startup",
    appliedDate: "12/04/2022",
    status: "pending",
  },
  {
    id: 4,
    name: "Debra Stewart",
    email: "d-s@gmail.com",
    phone: "1234567890",
    sex: "female",
    job_type: "full time",
    location: "Lahore",
    recruiter_name: "Darry",
    image: "",
    avatar_name: "DS",
    candidates: "2nd Interview",
    phase: "Startup",
    appliedDate: "12/04/2022",
    status: "unactive",
  },
  {
    id: 5,
    name: "Darry Day",
    email: "dd@gmail.com",
    phone: "1234567890",
    sex: "male",
    job_type: "part time",
    location: "Lahore",
    recruiter_name: "Zafar",
    image: "",
    avatar_name: "DD",
    candidates: "offer",
    phase: "Startup",
    appliedDate: "12/04/2022",
    status: "active",
  },
  {
    id: 6,
    name: "Susie Willis",
    email: "susie-w@gmail.com",
    phone: "1234567890",
    sex: "female",
    job_type: "part time",
    location: "Sargodha",
    recruiter_name: "Talha",
    image: "",
    avatar_name: "SW",
    candidates: "placed",
    phase: "Startup",
    appliedDate: "12/04/2022",
    status: "pending",
  },
  {
    id: 7,
    name: "Marshall Nichols",
    email: "marshall-n@gmail.com",
    phone: "1234567890",
    sex: "male",
    job_type: "full time",
    location: "Lahore",
    recruiter_name: "Talha",
    image: "",
    avatar_name: "MN",
    candidates: "renewals",
    phase: "Startup",
    appliedDate: "12/04/2022",
    status: "unactive",
  },
];
